/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pillulier;

import Classes.Case;
import fiducial.FiducialTracker;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import pillulier.utils.Codes;
import pillulier.utils.IdToCode;

/**
 *
 * @author fabien
 */
public class Main extends javax.swing.JFrame {

    private static Map<String, Case> cases = new HashMap<String, Case>();
    private static int retards = 0;
    private static int erreurs = 0;
    private static boolean aPrendre = false;
    private JFrame context = this;
    private JPanel currentPanel = null;
    
    /**
     * Creates new form Main
     */
    public Main() {
        
        try {
            System.setProperty( "file.encoding", "UTF-8" );
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        initMidPanel();
   
        jPanel1.setBorder(new EmptyBorder(10, 10, 10, 10) );
        jPanelInfos.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        initLegende();
                    
        runTimerTaskUpdateCases();    
        
        FiducialTracker ft = new FiducialTracker();
        ft.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog(this, true);
        jPanelDialog = new javax.swing.JPanel();
        jCheckBoxPriseMedicaments = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelinfo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelBot = new javax.swing.JPanel();
        jPanelLegende = new javax.swing.JPanel();
        jLabelBlanc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelVert = new javax.swing.JLabel();
        jLabelOrange = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelRouge = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelGris = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelBleu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelInfos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMedicamentsRetard = new javax.swing.JLabel();
        jLabelMedicamentsErreur = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelAPrendre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelMid = new javax.swing.JPanel();

        jDialog1.setAlwaysOnTop(true);

        jPanelDialog.setBackground(new java.awt.Color(254, 254, 254));

        jCheckBoxPriseMedicaments.setText("Prise de médicaments");
        jCheckBoxPriseMedicaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPriseMedicamentsActionPerformed(evt);
            }
        });

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabel12.setText("Médicaments à prendre :");

        jButton1.setText("Enregistrer");

        javax.swing.GroupLayout jPanelDialogLayout = new javax.swing.GroupLayout(jPanelDialog);
        jPanelDialog.setLayout(jPanelDialogLayout);
        jPanelDialogLayout.setHorizontalGroup(
            jPanelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDialogLayout.createSequentialGroup()
                .addGroup(jPanelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDialogLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addGroup(jPanelDialogLayout.createSequentialGroup()
                                .addGroup(jPanelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jCheckBoxPriseMedicaments))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanelDialogLayout.setVerticalGroup(
            jPanelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxPriseMedicaments)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelTop.setBackground(new java.awt.Color(254, 254, 254));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelinfo.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabelinfo.setText("Smart PillBoxOrganizer");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pillsmall.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(506, 506, 506))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelinfo)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBot.setBackground(new java.awt.Color(254, 254, 254));

        jLabelBlanc.setText("•");

        jLabel2.setText("Pas de prise de médicament");

        jLabelVert.setText("•");

        jLabelOrange.setText("•");

        jLabel8.setText("Médicaments pris par erreur");

        jLabelRouge.setText("•");

        jLabel10.setText("Prise de médicament oubliée");

        jLabelGris.setText("•");

        jLabel3.setText("Prise de médicament effectuée");

        jLabel6.setText("Prise de médicament à effectuer");

        jLabelBleu.setText("•");

        jLabel4.setText("Future prise de médicament");

        javax.swing.GroupLayout jPanelLegendeLayout = new javax.swing.GroupLayout(jPanelLegende);
        jPanelLegende.setLayout(jPanelLegendeLayout);
        jPanelLegendeLayout.setHorizontalGroup(
            jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLegendeLayout.createSequentialGroup()
                .addGroup(jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLegendeLayout.createSequentialGroup()
                        .addComponent(jLabelGris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanelLegendeLayout.createSequentialGroup()
                        .addComponent(jLabelRouge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanelLegendeLayout.createSequentialGroup()
                        .addComponent(jLabelOrange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBleu)
                    .addComponent(jLabelBlanc)
                    .addComponent(jLabelVert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelLegendeLayout.setVerticalGroup(
            jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLegendeLayout.createSequentialGroup()
                .addGroup(jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrange)
                    .addComponent(jLabel8)
                    .addComponent(jLabelBleu)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRouge)
                    .addComponent(jLabel10)
                    .addComponent(jLabelBlanc)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLegendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGris)
                    .addComponent(jLabel3)
                    .addComponent(jLabelVert)
                    .addComponent(jLabel6)))
        );

        jLabel1.setText("Prise de médicament en retard :");

        jLabelMedicamentsRetard.setText("0");

        jLabelMedicamentsErreur.setText("0");

        jLabel5.setText("Prise de médicament erronée :");

        jLabelAPrendre.setText("0");

        jLabel7.setText("Prise de médicament à effectuer maintenant :");

        javax.swing.GroupLayout jPanelInfosLayout = new javax.swing.GroupLayout(jPanelInfos);
        jPanelInfos.setLayout(jPanelInfosLayout);
        jPanelInfosLayout.setHorizontalGroup(
            jPanelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAPrendre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMedicamentsRetard))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMedicamentsErreur)))
                .addContainerGap())
        );
        jPanelInfosLayout.setVerticalGroup(
            jPanelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedicamentsErreur)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedicamentsRetard)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAPrendre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addComponent(jPanelLegende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jPanelInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelBotLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLegende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanelBot, java.awt.BorderLayout.PAGE_END);

        jPanelMid.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jPanelMid, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxPriseMedicamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPriseMedicamentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPriseMedicamentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void initMidPanel(){
        GridLayout layout = new GridLayout(4, 8);
        jPanelMid.setLayout(layout);
        jPanelMid.add(getTitreLabel(""));
        jPanelMid.add(getTitreLabel("Lundi"));
        jPanelMid.add(getTitreLabel("Mardi"));
        jPanelMid.add(getTitreLabel("Mercredi"));
        jPanelMid.add(getTitreLabel("Jeudi"));
        jPanelMid.add(getTitreLabel("Vendredi"));
        jPanelMid.add(getTitreLabel("Samedi"));
        jPanelMid.add(getTitreLabel("Dimanche"));
        
        jPanelMid.add(getTitreLigne("Matin"));
        jPanelMid.add(getJPanel(Codes.LUNDIMATIN));
        jPanelMid.add(getJPanel(Codes.MARDIMATIN));      
        jPanelMid.add(getJPanel(Codes.MERCREDIMATIN));
        jPanelMid.add(getJPanel(Codes.JEUDIMATIN));
        jPanelMid.add(getJPanel(Codes.VENDREDIMATIN));
        jPanelMid.add(getJPanel(Codes.SAMEDIMATIN));
        jPanelMid.add(getJPanel(Codes.DIMANCHEMATIN));

        jPanelMid.add(getTitreLigne("Midi"));
        jPanelMid.add(getJPanel( Codes.LUNDIMIDI));
        jPanelMid.add(getJPanel( Codes.MARDIMIDI));      
        jPanelMid.add(getJPanel( Codes.MERCREDIMIDI));
        jPanelMid.add(getJPanel( Codes.JEUDIMIDI));
        jPanelMid.add(getJPanel( Codes.VENDREDIMIDI));
        jPanelMid.add(getJPanel( Codes.SAMEDIMIDI));
        jPanelMid.add(getJPanel( Codes.DIMANCHEMIDI));
        
        jPanelMid.add(getTitreLigne("Soir"));
        jPanelMid.add(getJPanel(Codes.LUNDISOIR));
        jPanelMid.add(getJPanel(Codes.MARDISOIR));      
        jPanelMid.add(getJPanel(Codes.MERCREDISOIR));
        jPanelMid.add(getJPanel(Codes.JEUDISOIR));
        jPanelMid.add(getJPanel(Codes.VENDREDISOIR));
        jPanelMid.add(getJPanel(Codes.SAMEDISOIR));
        jPanelMid.add(getJPanel(Codes.DIMANCHESOIR));
        
        jPanelMid.setBorder(new EmptyBorder(0, 0, 10, 0) );
    }
    
    JPanel getTitreLigne(String titre){
        JPanel panel = new JPanel(new BorderLayout());
        
        JLabel label = new JLabel(titre);
        label.setFont (label.getFont ().deriveFont (18.0f));       
        panel.add(label, BorderLayout.CENTER);
        panel.setBackground(Color.WHITE);
        return panel;
    }
    
    JLabel getTitreLabel(String titre){
        JLabel label = new JLabel(titre, SwingConstants.CENTER);
        label.setFont (label.getFont ().deriveFont (18.0f));
        return label;
    }
    
    JPanel getJPanel(String code){
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(Color.decode("#c8c8c8"));
        
        JLabel labelLed = new JLabel("•");
        labelLed.setForeground(Color.WHITE);
        labelLed.setFont (labelLed.getFont ().deriveFont (100.0f));
        labelLed.setHorizontalAlignment(JLabel.CENTER);
        cases.put(code, new Case(code, labelLed));
        panel.add(labelLed, BorderLayout.CENTER);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        panel.addMouseListener(getMouseListener(code, panel));
        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxPriseMedicaments;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private static javax.swing.JLabel jLabelAPrendre;
    private javax.swing.JLabel jLabelBlanc;
    private javax.swing.JLabel jLabelBleu;
    private javax.swing.JLabel jLabelGris;
    private static javax.swing.JLabel jLabelMedicamentsErreur;
    private static javax.swing.JLabel jLabelMedicamentsRetard;
    private javax.swing.JLabel jLabelOrange;
    private javax.swing.JLabel jLabelRouge;
    private javax.swing.JLabel jLabelVert;
    private javax.swing.JLabel jLabelinfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelDialog;
    private javax.swing.JPanel jPanelInfos;
    private javax.swing.JPanel jPanelLegende;
    private javax.swing.JPanel jPanelMid;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    // End of variables declaration//GEN-END:variables

    private static void updateCases() {
        aPrendre = false;
        retards = 0;
        erreurs = 0;
        
        Iterator it = cases.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pairs = (Map.Entry)it.next();
            Case c = (Case) pairs.getValue();
            int res = c.updateCouleur();
            if(res == 1){
                aPrendre = true;
            }
            else if(res == -1){
                retards++;
            }
            else if(res == -2){
                erreurs++;
            }
        }
        
        updateAffichageInfo();
    }

    private static void updateAffichageInfo() {
        if(aPrendre){
            jLabelAPrendre.setText("1");
        }
        else{
            jLabelAPrendre.setText("0");
        }
        
        jLabelMedicamentsRetard.setText(String.valueOf(retards));
        jLabelMedicamentsErreur.setText(String.valueOf(erreurs));

    }

    private void initLegende() {
        jLabelBlanc.setForeground(Color.WHITE);
        jLabelBlanc.setFont (jLabelBlanc.getFont ().deriveFont (30.0f));
        jLabelBleu.setForeground(Color.BLUE);
        jLabelBleu.setFont (jLabelBleu.getFont ().deriveFont (30.0f));
        jLabelVert.setForeground(Color.GREEN);
        jLabelVert.setFont (jLabelVert.getFont ().deriveFont (30.0f));
        jLabelOrange.setForeground(Color.ORANGE);
        jLabelOrange.setFont (jLabelOrange.getFont ().deriveFont (30.0f));
        jLabelRouge.setForeground(Color.RED);
        jLabelRouge.setFont (jLabelRouge.getFont ().deriveFont (30.0f));
        jLabelGris.setForeground(Color.GRAY);
        jLabelGris.setFont (jLabelGris.getFont ().deriveFont (30.0f));
        
        jPanelLegende.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }

    /* 
    Mise à jour de l'affichage des cases et des infos
    */
    private void runTimerTaskUpdateCases() {
        
        TimerTask task = new TimerTask(){
	
            @Override
            public void run(){
                System.out.println("[Timer] Mise à jour information");
                updateCases();
            }	
	};
		
	Timer timer = new Timer();
	timer.scheduleAtFixedRate(task, 0, 1000*60*60);
    }
    
    public static void notificationChangementEtat(String idFiducial){
        IdToCode id = new IdToCode();
        String code = id.getCodeCase(idFiducial);
        cases.get(code).setMedicamentPri(true);
        updateCases();
    }
    
    private MouseListener getMouseListener(final String code, final JPanel panel){
        return new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent me) {
                
                currentPanel = panel;
                panel.setBackground(Color.BLACK);
                Case caseM = cases.get(code);
                jTextAreaDescription.setText(caseM.getDescription());
                jCheckBoxPriseMedicaments.setSelected(caseM.getMedicamentAPrendre());
                
                jDialog1.setSize(400, 366);
                jDialog1.setLocationRelativeTo(context);
                        
                if(jButton1.getActionListeners().length > 0){
                    jButton1.removeActionListener(jButton1.getActionListeners()[0]);
                }
                
                jButton1.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        Case caseM = cases.get(code);
                        caseM.setDescription(jTextAreaDescription.getText());
                        caseM.setMedicamentAPrendre(jCheckBoxPriseMedicaments.isSelected());     
                        panel.setBackground(Color.decode("#c8c8c8"));
                        jDialog1.setVisible(false);
                        updateCases();
                    }
                });
                
                jDialog1.setVisible(true);

            }

            @Override
            public void mousePressed(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
    }
   
}
